# GENERAL & NAVs
site_name: DjangoViews by Frank Arellano
nav:
  - Home: index.md
  - CBVs:
      - Overview: oop/overview.md
      - What Are CBVs?: oop/class/class.md
      - What Are Django Views?: oop/class/django_views.md
      - Traversing:
          - CustomLoginView: oop/traversing/login_view.md
          - CustomSignupView: oop/traversing/signup_view.md
          - CustomLogoutView: oop/traversing/logout_view.md
          - HomepageProductServiceView: oop/traversing/product_service_view.md
  - FBVs:
      - Overview: fbvs/overview.md
      - What Are FBVs?: fbvs/fbvs/fbvs.md
      - Traversing:
          - Placeholder: fbvs/traversing/placeholder.md
  - Snack:
      - Overview: snack/overview.md
      - Polymorphism: snack/polymorphism/polymorphism.md
      - Initialize MkDocs: snack/initialize/initial.md
  - About:
      - About Me: about/about.md
      - License: about/LICENSE.md
  - Credits:
      - Acknowledgement : credits/credits.md

# PLUGINS (bug present)
# plugins:
#   - glightbox

# THEME
theme:
  logo: assets/img/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: yellow

# EXTRA
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/plexoio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plexoio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arellanofrank/

# EXTENSIONS
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 by <a href="https://github.com/plexoio"  target="_blank" rel="noopener">Frank Arellano</a> 
  using 
  <a href="https://www.mkdocs.org/"  target="_blank" rel="noopener">MkDocs</a> & 